config/routes.rb
Rails.application.routes.draw do
  root "doctor#welcome"
  get "/doctors", to: "doctor#index"
  get "/home", to: "doctor#home"
  resources :doctor
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def index
	end

end

app/controllers/doctor_controller.rb
class DoctorController < ApplicationController
	def index
		@doctors = Doctor.all
	end

	def show
		@doctor = Doctor.find(params[:id])
	end

  	def new
  		@doctor = Doctor.new
  	end

  	def create
  		@doctor = Doctor.new(doctor_params)

  		if @doctor.save
    		redirect_to @doctor
    	else
    		render :new, status: :unprocessable_entity
    	end
  	end

	def edit
		@doctor = Doctor.find(params[:id])
	end

	def update
		@doctor = Doctor.find(params[:id])

		if @doctor.update(doctor_params)
			redirect_to @doctor
		else
			render :edit, status: :unprocessable_entity
		end
	end

	private
		def doctor_params
			params.require(:doctor).permit(:first_name, :last_name, :specialisation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/views/doctor/_form.html.erb
<div class="title-container">
  <%= form_with model: doctor do |form| %>
    <div>
      <%= form.label :first_name %><br>
      <%= form.text_field :first_name %>
      <% doctor.errors.full_messages_for(:first_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :last_name %><br>
      <%= form.text_field :last_name %><br>
      <% doctor.errors.full_messages_for(:last_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :specialisation %><br>
      <%= form.text_field :specialisation %>
    </div>

    <div>
      <br><%= form.submit class:"btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/doctor/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "E-Clinic", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", home_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Doctors", doctors_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/doctor/edit.html.erb
<div class='row py-4 px-5'>
	<div class='col-12 col-sm-5'>
		<h1>Edit Doctor</h1>
		<%= render "form", doctor: @doctor %>
	</div>
</div>

app/views/doctor/home.html.erb
<ul><br><br><br>
<div class="card" style="width: 18rem;">
		<%= image_tag "hospital.jpg", height: 150 %>
		<div class="card-body">
		  <h5 class="card-title">Some information about our facility...</h5>
		  <a href="#" class="btn btn-primary">Go for more</a>
		</div>
</div></ul>

app/views/doctor/index.html.erb
<div class='container-fluid'>
	<div class='row py-4 px-5'>
		<div class='col-12 col-sm-5'>
			<h3 class=''>The list of doctors:</h3>
			<table class="table table-bordered border-success table-hover table-success table-striped">
			  <thead>
			    <tr class="table-active">
			      <th scope="col">#</th>
			      <th scope="col">First Name</th>
			      <th scope="col">Last Name</th>
			    </tr>
			  </thead>
			  <tbody>
			  	<% @doctors.each do |doctor| %>
			  		<tr>
			  			<td><%= link_to doctor.id, doctor %></td>
			  			<td><%= doctor.first_name %></td>
			  			<td><%= doctor.last_name %></td>
			  		</tr>
			  	<% end %>
			  </tbody>
			</table>
		</div>
	</div>
</div>
<ul><ul><%= link_to "New Doctor", new_doctor_path, class:"btn btn-secondary" %></ul></ul>
  

app/views/doctor/new.html.erb
<div class='row py-4 px-5'>
	<div class='col-12 col-sm-5'>
		<h1>Adding New Doctor</h1><br>
		<%= render "form", doctor: @doctor %><br>
		<%= link_to "Back", doctors_path, class:"btn btn-secondary" %>
	</div>
</div>

app/views/doctor/show.html.erb
<div class='row py-4 px-5'>
	<div class='col-12 col-sm-3'>
		<div class="card">
		  <div class="card-header">
		    <%= image_tag "photo.jpg", height: 150 %>
		  </div>
		  <div class="card-body">
		    <h5 class="card-title"><%= @doctor.first_name %> <%= @doctor.last_name %></h5>
		    <p class="card-text">Specialisation: <%= @doctor.specialisation %></p>
		  </div>
		</div>
		<br>
		<%= link_to "Edit", edit_doctor_path, class:"btn btn-secondary" %>
		<%= link_to "Back", doctors_path, class:"btn btn-secondary" %>

	</div>
</div>

app/views/doctor/welcome.html.erb
<div class="text-center">
	<br><br><br>
	<%= image_tag "doctor.jpg", height: 250 %>
	<h1 class="display-1">Welcome to our clinic!</h1>
	<p class="lead"><strong>We are very pleased that you visited us. We invite you to make an appointment!</strong></p>
	<%= link_to "Let's see the doctors", doctors_path, class:"btn btn-success" %>
	
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>E-clinic App</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "doctor/header" %>
    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>